server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/journaldb
    username: journal_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: kafka:9092

logging:
  level:
    org.springframework: INFO

profiles:
  active: dev